id: PC90C0E6B
initial_creation_type: ocr
source_metadata:
  volumes:
    61b5a1323f3449c3b2aa7d3e93348b41:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་རྣམ་པར་གཏན་ལ་དབབ་པ་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
